name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Run Black
      run: black . --check
    - name: Run pyright
      uses: jakebailey/pyright-action@v1.8.1
    - name: Run pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest tests
